"""Valores oficiais do domínio de recorrências."""


PERIODICIDADE_MENSAL = "Mensal"
PERIODICIDADES_VALIDAS = (PERIODICIDADE_MENSAL,)

STATUS_RECORRENCIA_ATIVA = "Ativa"
STATUS_RECORRENCIA_PAUSADA = "Pausada"
STATUS_RECORRENCIA_CANCELADA = "Cancelada"

STATUS_RECORRENCIA_VALIDOS = (
    STATUS_RECORRENCIA_ATIVA,
    STATUS_RECORRENCIA_PAUSADA,
    STATUS_RECORRENCIA_CANCELADA,
)
