create table if not exists public.recorrencias (
    id bigint generated by default as identity primary key,
    descricao text not null,
    valor double precision null,
    tipo text not null,
    categoria text not null,
    forma_pagamento text not null,
    vencimento integer null,
    periodicidade text not null default 'Mensal',
    dia_programado integer not null,
    data_inicio date not null,
    data_fim date null,
    status_recorrencia text not null default 'Ativa',
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now(),
    constraint recorrencias_descricao_nao_vazia
        check (btrim(descricao) <> ''),
    constraint recorrencias_tipo_valido
        check (tipo in ('Receita', 'Despesa')),
    constraint recorrencias_categoria_valida
        check (categoria in (
            'Moradia', 'Utilidades', 'Mercado', 'Alimentação',
            'Transporte', 'Saúde', 'Educação', 'Família',
            'Lazer & Presentes', 'Cuidados pessoais', 'Dívidas',
            'Outros', 'Sem categoria'
        )),
    constraint recorrencias_forma_pagamento_valida
        check (forma_pagamento in ('PIX', 'Débito', 'Crédito', 'Dinheiro', 'Outro')),
    constraint recorrencias_vencimento_valido
        check (vencimento is null or vencimento between 1 and 31),
    constraint recorrencias_periodicidade_valida
        check (periodicidade = 'Mensal'),
    constraint recorrencias_dia_programado_valido
        check (dia_programado between 1 and 31),
    constraint recorrencias_data_fim_valida
        check (data_fim is null or data_fim >= data_inicio),
    constraint recorrencias_status_valido
        check (status_recorrencia in ('Ativa', 'Pausada', 'Cancelada')),
    constraint recorrencias_valor_valido
        check (valor is null or valor > 0)
);

alter table public.transacoes
    add column if not exists recorrencia_id bigint null,
    add column if not exists competencia_ocorrencia date null;

alter table public.transacoes
    add constraint transacoes_recorrencia_paridade_check
    check (
        (recorrencia_id is null and competencia_ocorrencia is null)
        or (recorrencia_id is not null and competencia_ocorrencia is not null)
    );

alter table public.transacoes
    add constraint transacoes_recorrencia_fk
    foreign key (recorrencia_id)
    references public.recorrencias(id)
    on delete restrict;

alter table public.transacoes
    add constraint transacoes_recorrencia_competencia_key
    unique (recorrencia_id, competencia_ocorrencia);

alter table public.recorrencias enable row level security;

grant select, insert, update on public.recorrencias to anon, authenticated, service_role;
grant usage, select on sequence public.recorrencias_id_seq to anon, authenticated, service_role;
